@Web_HostAddress = http://localhost:5116
@AuthPath = {{Web_HostAddress}}/api/auth
@BookPath = {{Web_HostAddress}}/api/book
@HealthPath = {{Web_HostAddress}}/api/health

@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiaXp6YXQiLCJleHAiOjE3MDY4MjgwODIsImlzcyI6IldlYkFwaUlzc3VlciIsImF1ZCI6IldlYkFwaUF1ZGllbmNlIn0.tXZYzp4Ikx28YeZ_z08tFVeCzR79PK1WQG-B2L6Erko

### Auth ###
GET {{AuthPath}}/login/izzat
Accept: text/plain

###

### Book ###
GET {{BookPath}}
Accept: application/json
Authorization: Bearer {{Token}}

###

GET {{BookPath}}/C7131631-2B58-758B-45B9-549EA6C92B93
Accept: application/json
Authorization: Bearer {{Token}}

###

### Health ###
GET {{HealthPath}}
Accept: application/json

###